### ISSUE TITLE
Примерная схема БД "Заявки"

### ISSUE THREAD

**Issue by Unlife86** [sorokinkir/intranet_project#3]
**Таблица с полями общими для всех заявок ("requests"):**

id
accepted_employee_id - foreign key table "employees"
address - string type. Адрес формируется из полей формы. Либо использовать дополнительные таблицы
type_request_id - foreign key table "types_requests"
responsible_employee_id - foreign key table "employees"
status_request_id - foreign key table "statuses_requests"

**Таблица добавляющая поля к заявкам на ремонт (низкая скорость, плохое качество ТВ), аварии (нет сигнала, нет доступа в интернет, подключение услуг, отключение КТВ, отключение КТВ, включение КТВ) ("client_info_requests")**

id 
request_id  - foreign key table "requests"
client_phone_number - integer type
time_interval_id - foreign key table "time_intervals"

**Таблица добавляющая описание к заявке (ремонт, авария и т.п.) (description_requests)**

id
request_id - foreign key table "requests"
description - text type. Описание заявки формируется из полей формы

**Таблица "employees"**

id 
full_name - string type. Полное имя сотрудника формируется из полей формы
employee_position_id - foreign key table "employees_positions"

**Таблицы "types_requests", "statuses_requests", "time_intervals", "employees_positions"**

id
name - string type

**Comment by sorokinkir** [comment]
Нужно по каждому полю подробнее.

**Comment by Unlife86** [comment]
Обновил

**Comment by sorokinkir** [comment]
Блин, стена текста, разбей ее по таблицам и полям в этих таблицах, будь любезен ;)

**Comment by Unlife86** [comment]
Обновил

**Comment by sorokinkir** [comment]
Посмотри на это:
[https://github.com/sorokinkir/intranet_project/blob/master/catalog_repair/models.py](url)

**Comment by Unlife86** [comment]
Да, вот историю я не учел, надо подумать

**Comment by sorokinkir** [comment]
Issue закрываю, т.к. с бд в общем для работы уже все сделано.
